import { Product, ProductCategory } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  // Existing Products with updated image seeds
  {
    id: '1',
    name: 'AuraWatch Series X',
    price: 399.99,
    description: 'The latest smartwatch with advanced health tracking and seamless connectivity.',
    imageUrl: 'https://picsum.photos/seed/AuraWatchSeriesX/400/300',
    category: ProductCategory.ELECTRONICS,
  },
  {
    id: '2',
    name: 'EchoBuds Pro',
    price: 129.99,
    description: 'Wireless earbuds with immersive sound and noise cancellation technology.',
    imageUrl: 'https://picsum.photos/seed/EchoBudsPro/400/300',
    category: ProductCategory.ELECTRONICS,
  },
  {
    id: '3',
    name: 'Urban Explorer Hoodie',
    price: 79.50,
    description: 'Comfortable and stylish hoodie, perfect for everyday adventures.',
    imageUrl: 'https://picsum.photos/seed/UrbanExplorerHoodie/400/300',
    category: ProductCategory.APPAREL,
  },
  {
    id: '4',
    name: 'Minimalist Desk Lamp',
    price: 59.00,
    description: 'Sleek LED desk lamp with adjustable brightness for your modern workspace.',
    imageUrl: 'https://picsum.photos/seed/MinimalistDeskLamp/400/300',
    category: ProductCategory.HOME_GOODS,
  },
  {
    id: '5',
    name: 'The Cosmic Labyrinth',
    price: 19.99,
    description: 'A thrilling science fiction novel that will transport you to other worlds.',
    imageUrl: 'https://picsum.photos/seed/TheCosmicLabyrinth/400/300',
    category: ProductCategory.BOOKS,
  },
  {
    id: '6',
    name: 'ProBalance Yoga Mat',
    price: 34.99,
    description: 'Eco-friendly, non-slip yoga mat for your daily practice.',
    imageUrl: 'https://picsum.photos/seed/ProBalanceYogaMat/400/300',
    category: ProductCategory.SPORTS,
  },
  {
    id: '7',
    name: 'Radiant Glow Serum',
    price: 45.00,
    description: 'A rejuvenating facial serum for a healthy, radiant complexion.',
    imageUrl: 'https://picsum.photos/seed/RadiantGlowSerum/400/300',
    category: ProductCategory.BEAUTY,
  },
  {
    id: '8',
    name: 'TechPro Backpack',
    price: 89.99,
    description: 'Durable and spacious backpack with multiple compartments for your gadgets.',
    imageUrl: 'https://picsum.photos/seed/TechProBackpack/400/300',
    category: ProductCategory.ELECTRONICS,
  },
  {
    id: '9',
    name: 'ComfyKnit Sneakers',
    price: 119.00,
    description: 'Lightweight and breathable sneakers for ultimate comfort.',
    imageUrl: 'https://picsum.photos/seed/ComfyKnitSneakers/400/300',
    category: ProductCategory.APPAREL,
  },
  {
    id: '10',
    name: 'Smart Coffee Maker',
    price: 149.50,
    description: 'Wi-Fi enabled coffee maker that brews your perfect cup on schedule.',
    imageUrl: 'https://picsum.photos/seed/SmartCoffeeMaker/400/300',
    category: ProductCategory.HOME_GOODS,
  },
  // New Products
  {
    id: '11',
    name: 'Portable SSD 1TB',
    price: 89.99,
    description: 'Ultra-fast and compact portable SSD for your data on the go.',
    imageUrl: 'https://picsum.photos/seed/PortableSSD1TB/400/300',
    category: ProductCategory.ELECTRONICS,
  },
  {
    id: '12',
    name: 'Precision Gaming Mouse',
    price: 59.99,
    description: 'Ergonomic gaming mouse with customizable DPI and RGB lighting.',
    imageUrl: 'https://picsum.photos/seed/PrecisionGamingMouse/400/300',
    category: ProductCategory.ELECTRONICS,
  },
  {
    id: '13',
    name: 'Organic Linen Shirt',
    price: 65.00,
    description: 'Breathable and stylish organic linen shirt for a relaxed look.',
    imageUrl: 'https://picsum.photos/seed/OrganicLinenShirt/400/300',
    category: ProductCategory.APPAREL,
  },
  {
    id: '14',
    name: 'Classic Leather Belt',
    price: 45.00,
    description: 'Genuine leather belt, a timeless accessory for any outfit.',
    imageUrl: 'https://picsum.photos/seed/ClassicLeatherBelt/400/300',
    category: ProductCategory.APPAREL,
  },
  {
    id: '15',
    name: 'Smart Home Thermostat',
    price: 199.00,
    description: 'Energy-saving smart thermostat controllable via your smartphone.',
    imageUrl: 'https://picsum.photos/seed/SmartHomeThermostat/400/300',
    category: ProductCategory.HOME_GOODS,
  },
  {
    id: '16',
    name: 'Industrial Bookshelf',
    price: 120.00,
    description: 'Sturdy and stylish bookshelf with a modern industrial design.',
    imageUrl: 'https://picsum.photos/seed/IndustrialBookshelf/400/300',
    category: ProductCategory.HOME_GOODS,
  },
  {
    id: '17',
    name: 'The Art of Focus',
    price: 15.99,
    description: 'A guide to mastering attention and productivity in a distracted world.',
    imageUrl: 'https://picsum.photos/seed/TheArtOfFocusBook/400/300',
    category: ProductCategory.BOOKS,
  },
  {
    id: '18',
    name: 'Culinary Journeys',
    price: 24.50,
    description: 'Explore world cuisines with this beautifully illustrated cookbook.',
    imageUrl: 'https://picsum.photos/seed/CulinaryJourneysBook/400/300',
    category: ProductCategory.BOOKS,
  },
  {
    id: '19',
    name: 'Adjustable Dumbbell Set',
    price: 150.00,
    description: 'Versatile dumbbell set, perfect for a home gym setup.',
    imageUrl: 'https://picsum.photos/seed/AdjustableDumbbellSet/400/300',
    category: ProductCategory.SPORTS,
  },
  {
    id: '20',
    name: 'Resistance Band Kit',
    price: 25.99,
    description: 'Set of 5 resistance bands for a full-body workout anywhere.',
    imageUrl: 'https://picsum.photos/seed/ResistanceBandKit/400/300',
    category: ProductCategory.SPORTS,
  },
  {
    id: '21',
    name: 'Hydrating Night Cream',
    price: 38.00,
    description: 'Rich night cream to repair and hydrate your skin overnight.',
    imageUrl: 'https://picsum.photos/seed/HydratingNightCream/400/300',
    category: ProductCategory.BEAUTY,
  },
  {
    id: '22',
    name: 'Nourishing Hair Mask',
    price: 22.50,
    description: 'Deep conditioning hair mask for soft, shiny, and healthy hair.',
    imageUrl: 'https://picsum.photos/seed/NourishingHairMask/400/300',
    category: ProductCategory.BEAUTY,
  },
  // New Category: Outdoors
  {
    id: '23',
    name: 'AllWeather Camping Tent',
    price: 179.99,
    description: 'Durable 2-person tent, waterproof and easy to set up.',
    imageUrl: 'https://picsum.photos/seed/AllWeatherCampingTent/400/300',
    category: ProductCategory.OUTDOORS,
  },
  {
    id: '24',
    name: 'TrailBlazer Hiking Boots',
    price: 129.50,
    description: 'Comfortable and rugged hiking boots for all terrains.',
    imageUrl: 'https://picsum.photos/seed/TrailBlazerHikingBoots/400/300',
    category: ProductCategory.OUTDOORS,
  },
  {
    id: '25',
    name: 'Explorer Kayak Set',
    price: 349.00,
    description: 'Inflatable kayak set for one person, includes paddle and pump.',
    imageUrl: 'https://picsum.photos/seed/ExplorerKayakSet/400/300',
    category: ProductCategory.OUTDOORS,
  }
];

export const CATEGORIES: ProductCategory[] = Object.values(ProductCategory);
